Description: Networking architecture

Parameters:
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: "10.0.0.0/22"
  PubSubnetACidr:
    Type: String
    Default: "10.0.0.0/24"
  StudentName:
    Type: String
    Default: "EV-FB"

Resources:

# VPC
  EVFBVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub "EVFBVPC"

  PubSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref EVFB-VPC
      CidrBlock: !Ref PubSubnetACidr
      AvailabilityZone: "eu-west-2a"
      Tags:
        - Key: Name
          Value: !Sub "EV-FB-pub-subnet-A"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "EV-FB-igw"


  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref EV-FB-VPC
      InternetGatewayId: !Ref InternetGateway

  PubRouteA:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "EV-FB-RouteTable-Pub-A"
      VpcId: !Ref EV-FB-VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
        RouteTableId: !Ref PubRouteA
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

  PubSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PubRouteA
      SubnetId: !Ref PubSubnetA


# EC2 instance
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0d76271a8a1525c1a"
      InstanceType: "t2.micro"
      KeyName: "my-keypair"
      SubnetId: !Ref PubSubnetA 
      UserData: !Base64 |
        #!/bin/bash
        cat ec2-user-data.sh
